// js/pages/reports.js

function formatMAD(value) {
  const number = Number(value || 0);
  return `${number.toLocaleString("fr-MA")} MAD`;
}

function getSelectedPeriod() {
  return document.getElementById("period").value;
}

function getReport() {
  const data = CFOStorage.load();
  const period = getSelectedPeriod();
  return ReportEngine.generateReport(data, period);
}

function renderReportCards(report) {
  document.getElementById("reportIncome").textContent =
    formatMAD(report.estimatedIncome);

  document.getElementById("reportTransactions").textContent =
    formatMAD(report.transactionSpending);

  document.getElementById("reportBills").textContent =
    formatMAD(report.proRataFixedBills);

  document.getElementById("reportSavings").textContent =
    formatMAD(report.realSavings);
}

function setAnswer(title, message) {
  const answerTitle = document.getElementById("answerTitle");
  const answerText = document.getElementById("answerText");

  if (!answerTitle || !answerText) return;

  answerTitle.textContent = title;

  // Important: message contains internal HTML generated by our app
  answerText.innerHTML = message;
}

function renderDetails(items = []) {
  const container = document.getElementById("detailsList");

  if (!container) return;

  if (items.length === 0) {
    container.innerHTML = `
      <div class="card">
        <p style="margin:0;color:#6b7280;">No details to show yet.</p>
      </div>
    `;
    return;
  }

  container.innerHTML = items.map(item => {
    return `
      <div class="list-item">
        <div>
          <strong>${item.title}</strong><br>
          <small>${item.subtitle || ""}</small>
        </div>
        <strong>${item.value || ""}</strong>
      </div>
    `;
  }).join("");
}

function showStandardReport() {
  const report = getReport();
  renderReportCards(report);

  const status = report.realSavings >= 0 ? "positive" : "negative";

  setAnswer(
    "Standard CFO Report",
    `From ${report.startDate} to ${report.endDate}, your estimated income was ${formatMAD(report.estimatedIncome)}, your total expenses were ${formatMAD(report.totalExpenses)}, and your savings were ${formatMAD(report.realSavings)}. Your savings are ${status}.`
  );

  const categoryItems = Object.entries(report.byCategory).map(([category, amount]) => ({
    title: category,
    subtitle: "Spending by category",
    value: formatMAD(amount)
  }));

  renderDetails(categoryItems);
}

function askCouldHaveSaved() {
  const report = getReport();
  renderReportCards(report);

  const opportunity = SavingOpportunityEngine.calculatePossibleSavings(
    report.transactions
  );

  const potentialSavings = report.realSavings + opportunity.possibleSaving;

  setAnswer(
    "How much could I have saved?",
    `You saved ${formatMAD(report.realSavings)} in this period. Based on your lifestyle expenses, you could have saved around ${formatMAD(opportunity.possibleSaving)} more. Potential savings: ${formatMAD(potentialSavings)}.`
  );

  renderDetails([
    {
      title: "Lifestyle spending",
      subtitle: "Spending marked as lifestyle",
      value: formatMAD(opportunity.lifestyleTotal)
    },
    {
      title: "Possible extra saving",
      subtitle: "Estimated by reducing lifestyle spending by 30%",
      value: formatMAD(opportunity.possibleSaving)
    },
    {
      title: "Potential total savings",
      subtitle: "Real savings + possible extra saving",
      value: formatMAD(potentialSavings)
    }
  ]);
}

function askWhereLostMoney() {
  const report = getReport();
  renderReportCards(report);

  const leaks = SavingOpportunityEngine.findTopLeakCategories(
    report.transactions
  );

  if (leaks.length === 0) {
    setAnswer(
      "Where did I lose money?",
      "No lifestyle money leaks detected in this period. Add more daily expenses to get better analysis."
    );

    renderDetails([]);
    return;
  }

  const top = leaks[0];

  setAnswer(
    "Where did I lose money?",
    `Your biggest money leak was ${top.category}, with ${formatMAD(top.amount)} in lifestyle spending during this period.`
  );

  renderDetails(
    leaks.map(item => ({
      title: item.category,
      subtitle: "Top lifestyle money leak",
      value: formatMAD(item.amount)
    }))
  );
}

function askWhatReduce() {
  const report = getReport();
  renderReportCards(report);

  const plan = SavingOpportunityEngine.generateReductionPlan(
    report.transactions
  );

  if (plan.length === 0) {
    setAnswer(
      "What should I reduce?",
      "Your CFO does not see enough lifestyle spending to create a reduction plan yet."
    );

    renderDetails([]);
    return;
  }

  const totalSuggestedCut = plan.reduce((sum, item) => {
    return sum + item.suggestedCut;
  }, 0);

  setAnswer(
    "What should I reduce?",
    `Start by reducing your top lifestyle categories. You could save around ${formatMAD(totalSuggestedCut)} by cutting these categories by 30%.`
  );

  renderDetails(
    plan.map(item => ({
      title: item.category,
      subtitle: `Current: ${formatMAD(item.currentSpending)} → Target: ${formatMAD(item.newTarget)}`,
      value: `Save ${formatMAD(item.suggestedCut)}`
    }))
  );
}

function askSpendingFast() {
  const data = CFOStorage.load();
  const report = getReport();
  renderReportCards(report);

  const speed = SavingOpportunityEngine.analyzeSpendingSpeed(data);

  let message = "";

  if (speed.status === "Spending too fast") {
    message = `You are spending too fast this month. You spent ${formatMAD(speed.spentSoFar)}, but based on your envelope budget, expected spending by today is around ${formatMAD(speed.expectedSpending)}. You are ahead by ${formatMAD(speed.pacingDelta)}.`;
  } else if (speed.status === "Under budget") {
    message = `You are under budget. You spent ${formatMAD(speed.spentSoFar)}, while your expected spending by today is around ${formatMAD(speed.expectedSpending)}. Good control.`;
  } else {
    message = `You are on track. Your spending is close to the expected pace for this month.`;
  }

  setAnswer("Am I spending too fast?", message);

  renderDetails([
    {
      title: "Envelope budget",
      subtitle: "Total monthly flexible budget",
      value: formatMAD(speed.envelopeTotal)
    },
    {
      title: "Spent so far",
      subtitle: "Daily transactions this month",
      value: formatMAD(speed.spentSoFar)
    },
    {
      title: "Expected spending by today",
      subtitle: "Based on month progress",
      value: formatMAD(speed.expectedSpending)
    },
    {
      title: "Pacing difference",
      subtitle: speed.status,
      value: formatMAD(speed.pacingDelta)
    }
  ]);
}
function askDiagnosis() {
  const data = CFOStorage.load();
  const report = getReport();

  const diagnosis = DiagnosisEngine.generate(data, report);

  renderReportCards(report);

  setAnswer(
    diagnosis.verdict,
    `
      <strong>CFO Diagnosis</strong><br><br>

      <strong>What the numbers say:</strong><br>
      ${diagnosis.facts.map(fact => `• ${fact}`).join("<br>")}

      <br><br>

      <strong>Main risks:</strong><br>
      ${diagnosis.risks.map(risk => `• ${risk}`).join("<br>")}

      <br><br>

      <strong>Next CFO actions:</strong><br>
      ${diagnosis.actions.map(action => `• ${action}`).join("<br>")}

      <br><br>

      <strong>Conclusion:</strong><br>
      Your biggest category is ${diagnosis.topCategory.category}.
      Lifestyle ratio is ${diagnosis.lifestyleRatio}% of daily transactions.
    `
  );
}
function runActionFromUrl() {
  const params = new URLSearchParams(window.location.search);

  const action = params.get("action");
  const period = params.get("period");

  const periodSelect = document.getElementById("period");

  if (period && periodSelect) {
    periodSelect.value = period;
  }
if (action === "diagnosis") {
  askDiagnosis();
  return;
}
  if (action === "saved") {
    askCouldHaveSaved();
    return;
  }

  if (action === "lost") {
    askWhereLostMoney();
    return;
  }

  if (action === "reduce") {
    askWhatReduce();
    return;
  }

  if (action === "fast") {
    askSpendingFast();
    return;
  }

  showStandardReport();
}


function initReportsPage() {
  const params = new URLSearchParams(window.location.search);
  const action = params.get("action");
  const period = params.get("period");

  const periodSelect = document.getElementById("period");

  if (period && periodSelect) {
    periodSelect.value = period;
  }

  const periodChangeHandler = () => {
    askDiagnosis();
  };

  if (periodSelect) {
    periodSelect.addEventListener("change", periodChangeHandler);
  }

  if (action === "saved") {
    askCouldHaveSaved();
    return;
  }

  if (action === "lost") {
    askWhereLostMoney();
    return;
  }

  if (action === "reduce") {
    askWhatReduce();
    return;
  }

  if (action === "fast") {
    askSpendingFast();
    return;
  }

  if (action === "diagnosis") {
    askDiagnosis();
    return;
  }

  // Default reports perspective
  askDiagnosis();
}

document.addEventListener("DOMContentLoaded", initReportsPage);